etcd:
  image: autopilotpattern/etcd
  mem_limit: 128m
  ports:
    - 4001
    - 2379
    - 2380
  labels:
    - triton.cns.services=etcd
  environment:
    - DISCOVERY
  command: >-
    /usr/local/bin/etcd-manage start

bootstrap:
  image: autopilotpattern/etcd
  mem_limit: 128m
  ports:
    - 4001:4001
    - 2379:2379
    - 2380:2380
  command: >-
    /usr/local/bin/etcd-manage bootstrap
